# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_Uj_UvLefZVgkdtLW8n9NIp_5lKghJn
"""

#HW1-1 튜플형 데이 (A,B)를 만들고 C를 추가한다.
x = ('A', 'B')
temp_list = list(x)
temp_list.append('C')
tuple(temp_list)
print(type(x))
print(type(temp_list))

#HW1-2
import numpy as np
n = int(input())
A = np.zeros((n,n)) #초기화 지정
for i in range(n):
  for j in range(n):
    A[i][j] = i*n + j
print(A)

#HW1-3
import numpy as np
n = int(input())
A = np.zeros((n,n)) #초기화 지정
for i in range(n):
  for j in range(n):
    A[i][j] = i*n + j
print(A)
B = A.reshape(-1, )

#HW1-4
import cv2 # 이미지 읽기 위함 라이브러리
import numpy as np
img = cv2.imread("Lenna.png")
print("original",img.shape)
img1 = np.expand_dims(img, 0) #batch부터 추가 차원 동기화를 해주려고 차원추가를 사용함
img1_1 = np.squeeze(img) #batch부터 추가 차원 동기화를 차원을 빼줄 수 있음
img2 = np.transpose(img1, (0,3,1,2)) #데이터 값을 어떤 순서 넣을지
print("expand", img1.shape)
print("squeeze", img1_1.shape)
print("transpose", img2.shape)