# -*- coding: utf-8 -*-
"""hw4-python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuI-Z6LDUVXm0Jst3MljAwbOe5ycLWrm
"""

tup=('A','B')
tup2=('C',)
tup+=tup2
print(tup)

import numpy as np
n =int(input())
A=np.zeros((n,n))
for i in range(n):
  for j in range(n):
    A[i,j]=i*n+j+1
print(A)

B=A.reshape(-1,)
print(B)

import cv2
frame=cv2.imread("Lenna.png",cv2.COLOR_BGR2RGB)

frame1=np.expand_dims(frame,0)
frame2=np.permute_dims(frame1,(0,3,1,2))
print('original',frame.shape)

print('expand dims',frame1.shape)
print('transpose',frame2.shape)



# add practice python 

thistuple=("apple","banana","cherry")
print(thistuple[1])
for x in thistuple:
  print(x)
tuple1=("abc",34,True,40,"male","abc")
print(tuple1[2])
a=1,
b=1
print(type(a),type(b))
print(a,b)

tuple1=("a","b","c")
tuple2=(1,2,3)
tuple3=tuple1+tuple2
tuple4=tuple2*2
print(tuple3,tuple4)

thistuple=("apple","banana","cherry","orange","kiwi","melon","mango")
print(thistuple[1])

thistuple=("apple","banana","cherry","orange","kiwi","melon","mango")
print(thistuple[2:5])

x=("apple","banana","cherry")
y=list(x)
y[1]="kiwi"
x=tuple(y)
print(x)

a=[1,3,4]
print(a)
a[0]=9
print(a)

b=[1,3,'string']
print(b)
b.append(6.24)
print(b)

print(2*a)
print(b*2)
c=[a[i]+a[i] for i in range(len(a))]
print(c)

thisdict={
    # key : value
    "brand": "Ford",
    "model": "Mustang",
    "year": 1964
}
print(thisdict["brand"])
print(type(thisdict))

#for loop

items=[1,2,3,4,"Hello",6.24]

for k in range(0,len(items)):
  print(items[k])
print('-----------')
for item in items:
  print(item)
info={'A':1,'B':2,'C':3}
for key in info:
  print(key,info[key])
for key, value in info.items():
  print(key,value)

items1=[[1,2],[3,4],[5,6]]
items2=[['A','B'],['C','D'],['E','F']]
print(items1)
print(items2)
print('---------------------')
for digits,characters in zip(items1,items2):
  print(digits,characters)

a=[]
for k in range(0,5):
  a.append(k)
print(a)
print('-------------------------')
a=[k for k in range(0,5)]
print(a)
print('-------------------------')
a=[k if (k+1)%2 else k*5+1 for k in range(0,5)]
print(a)
print('-------------------------')
a={k:k*10 for k in range(0,5)}
print(a)
print('-------------------------')
a=[1,3,4]
c=[a[i]+a[i] for i in range(len(a))]
print(c)

import numpy as np
from numpy import linalg as LA
c=np.array([[1,2,3],[-1,1,4]])
print(LA.norm(c,axis=0))
print(LA.norm(c,axis=1))
print(LA.norm(c,ord=1,axis=1))
print(LA.norm(c,ord=2,axis=1))



#numpy array
import numpy as np
a=np.array([1,2,3,4]) # list -> numpy array trans
print('numpy array')
print(a)
print(a+a)
print()
print('list')
#list
b=[1,2,3,4]
print(b+b)

#two dimensional array
a=np.array([[1,2],[3,4]])
print(a)
#tree dimensional array
print()
print('tree dimension')
a=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(a)

a=np.array([1,2,3,4])
b=np.array([[1],[2],[3],[4]])
print(a)
print(a.shape)
print(b)
print(b.shape)

import numpy as np
from numpy import linalg as LA
c=np.array([[1,2,3],
            [-1,1,4]])
print(LA.norm(c,axis=0))
print(LA.norm(c,axis=1))
print(LA.norm(c,ord=1,axis=1))
print(LA.norm(c,ord=2,axis=1))

a=np.array([[1],[2],[3],[4]])
print(a)
print(a.T)
print(a.T.reshape(-1,4))
print(a.shape)
print(a.T.reshape(-1,4).T.shape)

a=np.array([1,2,3,4])
b=a.reshape(4,-1)
print(a)
print(a.reshape(2,-1))
print(a.shape,",",b.shape,",",np.array([[1,2,3,4]]).shape)

a=np.array([1,2,3,4,5,6])
print(a.reshape(3,2))
print(a.shape)
b=a.reshape(3,-1)
print(b)
print(b.shape)
c=a.reshape(-1,2)
print(c)
print(c.shape)

a=np.array([1,2,3,4,])
print(a)
print(a.T)
b=a.reshape(4,-1)
print(b.shape)
print(b)
print(b.T.shape)

a=np.array([10,20,30,40,50,60])
print(a)
b=a[[4,2,0]]
print(b)
idx=np.arange(0,len(a))
print(idx)
np.random.shuffle(idx)
print(idx)
print(a[idx])

word='Python'
print(word[0])
print(word[5])
print(word[-1])
print(word[-2])
print(word[-6])
print(word[0:2])
print(word[2:5])
print(word[:2])
print(word[4:])
print(word[-2:])
print(word[:2]+word[2:])
print(word[:4]+word[4:])

A=np.array([[1,4,2,0],[9,5,0,0],[4,0,2,4],[6,1,8,3]])
x=np.array([1,2,3,4])
b=np.array([0,0,0,0])
n=4
for i in range(0,n):
  val=0.0
  for j in range(0,n):
    val+=A[i,j]*x[j]
  b[i]=val

print("calculate=",b)
b=np.dot(A,x)
print("dot=",b)

b=np.matmul(A,x)
print("matmul=",b)

b=A@x
print("A@x=",b)

b=A*x
print("A*x=",b)

import numpy as np
A=np.array([[1,4,2,0],[9,5,0,0],[4,0,2,4],[6,1,8,3]])
b=np.array([15,19,26,44])

print("det=",np.linalg.det(A))

x=np.linalg.solve(A,b)
print("solver =",x)
tmp_b=np.dot(A.T,b)
tmp_T=np.dot(A.T,A)
tmp_inv=np.linalg.inv(np.dot(A.T,A))
x=np.dot(tmp_inv,tmp_b)
print("inverse2 =",x)
