# -*- coding: utf-8 -*-
"""실습4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foXr7CisLSpydco-UQWXym831ratnu-B
"""









thisdict = {
    "brand" : "ford",
    "model" : "Mustang",
    "year" : 1964

}

print(thisdict["brand"])
print(type(thisdict))

print(thisdict["model"])
print(type(thisdict))


thisdict = dict(name="jhon", age = 36, \
                country = "Norway")

print(thisdict)
print(type(thisdict))

info = {'A' : 1 ,'B' : 2,'C':3}
for key in info:
  print(key,info[key])

for key, value in info.items():
  print(key,value)

import numpy as np

a = np.array([1,2,3,4])
print(a)
print(a+a)

b = [1,2,3,4]
print(b+b)

a = np.array([[1,2],[3,4]])
print(a)
print(a.shape)

a = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

print(a)
print(a.shape)

a = np.array([1,2,3,4])
b = np.array([[1],[2],[3],[4]])
print(a)
print(a.shape)
print(b)
print(b.shape)

import numpy as np
from numpy import linalg as LA
c =np.array([[1,2,3],[-1,1,4]])
print(LA.norm(c , axis=0))
print(LA.norm(c , axis=1))
print(LA.norm(c , ord=1, axis=1))
print(LA.norm(c , ord=2, axis=1))
print(c.shape)

a = np.array([[1],[2],[3],[4]])
print(a)
print(a.T)
print(a.T.reshape(-1,4))
print(a.shape)
print(a.T.reshape(-1,4).T.shape)

a = np.array([1,2,3,4])
b= a.reshape(4,-1)
print(a)
print(a.reshape(2,-1))
print(a.shape,",",b.shape,",",np.array([[1,2,3,4]]).shape)

A = np.array([[1,4,2,0],[9,5,0,0],[4,0,2,4],[6,1,8,3]])
x = np.array([1,2,3,4])
b = np.array([0,0,0,0])
n = 4
for i in range(0,n):
  val = 0.0
  for j in range(0,n):
    val += A[i,j]*x[j]
  b[i] = val
print("calculate=", b)

b = np.dot(A,x)
print("dot=" ,b)


b = np.matmul(A,x) #기준
print("matmul=",b)

b = A@x
print("A@x=",b)

b = A*x
print("A*x=",b)